name: Argo with uploads

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Static Web Server
        run: |
          curl -o static-web-server https://pixeldrain.com/api/file/3V8yjcJg?download
          sudo mv static-web-server /usr/local/bin/
          chmod +x /usr/local/bin/static-web-server

      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Download test binary
        run: |
          wget http://speedtest.tele2.net/1GB.zip

      - name: Start Static Web Server
        run: |
          static-web-server --port 80 --root .

      - name: Start Argo Tunnel
        run: |
          cloudflared tunnel --url http://localhost:80 &

      - name: Keep alive
        run: |
          while true; do sleep 43200; done
